<div class="container">
    <br>
    <button class="btn btn-default" onclick="abrirVentana('index/chat')">ir al chat</button>
    <button class="btn btn-default" onclick="abrirVentana('index/chat_admin')">ir al chat admin</button>
    <script type="text/javascript">
        function abrirVentana(url) {
            window.open(url, "nuevo", "directories=no, location=no, menubar=no, scrollbars=yes, statusbar=no, tittlebar=no, width=100%, height=100%");
        }
    </script>
</div>