<script type="text/javascript">
	window.onload = function(){
		resizeTo(screen.width, screen.height)
		moveTo(0, 0);
	}
</script>
<style type="text/css">
	body{
		background-color:#E0E0E0;
	}
</style>
<center>
  		<?php echo Html::img("logo.png") ?>
		<h2>Administrador para chat</h2>
  		<p>
  			<?php echo $mensaje ?>
  		</p>
  		</center>
<div class="row" style="padding:10px">
  <div class="col-md-4">
  	<ul class="list-group" id="mensajes_de_canales">
  			<?php foreach ($salas as $key => $value): ?>
		  		<li class="list-group-item"><img width="50" src="<?php echo $value->gravatar ?>" alt=""> <?php echo $value->nombre." ( ".$value->email.") " ?>
				
		  			<div class="pull-right">
						<input type="button" class="btn btn-default btn-xs ver_mensajes" codigo="<?php echo $value->identificador_canal ?>" id="<?php echo $value->usuario_id ?>" value="Ver Mensajes">
						<input type="button" class="btn btn-default btn-xs eliminar_mensajes" codigo="<?php echo $value->identificador_canal ?>" id="<?php echo $value->usuario_id ?>" value="Eliminar Mensajes">
		  			</div>
		  			<div class="clearfix"></div>
		  		</li>
  			<?php endforeach ?>			
		</ul>
  </div>
  <div class="col-md-4">
		<div class="well">
		<div class="well" id="zona_mensajes" codigo="co;o" usuario="mierda" style="height:350px;overflow:scroll">
			
		</div>
		<div class="form-group">
			<input type="text" name="mensaje" id="mensaje" placeholder="Escribe aqui, luego presiona ENTER" class="form-control mensaje">
		</div>
		<div class="pull-left">
			<div class="check">
				<label>
					<input type="checkbox" id="mute"> Silenciar
				</label>
			</div>
		</div>
		<div class="pull-right">
			<input type="submit" onclick="window.close()" name="ingresar" value="Cerrar Chat" class="btn btn-default">
		</div>

		<div class="clearfix"></div>
	</div>	
  </div>
  <div class="col-md-4">
  	<div class="form-group">
  		<label> Gravatar </label>
  		<input type="text" id="gravatar_admin" placeholder="Copiar url de gravatar para administrador" class="form-control">
  	</div>
  	<div class="pull-right">
		<input type="button" id="cargar_imagen" class="btn btn-default" value="Cargar Imagen">
  	</div>
  	<div class="clearfix"></div>
  	<div class="row">
	  	<hr>
	  	<center>
	    <?php echo Html::img("user_256.png","","style='width:200px !important;' id='imagen_gravatar'") ?>
	    </center>
	</div>
  </div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$("body").on("keyup",".mensaje",function(e){
			var tecla = e.keyCode;
			
			if (tecla == 13) {
				mandarMensaje($(this).val(),$(this));
			}
			
		});
		
		$("body").on("click",".ver_mensajes",function(){
			var id = $(this).attr("id");
			var codigo = $(this).attr("codigo");
			$.ajax({
				url:"get_mensajes_canal",
				type:"POST",
				data:{codigo:$(this).attr("codigo")},
				async:false,
				dataType:'json',
				success:function(r){
					mensajes = r;
					$("#zona_mensajes").html("");
		
					for (var i = 0; i < mensajes.length; i++) {
					
						$("#zona_mensajes").append(mensajes[i].mensaje);
					};
					if (mensajes[0].disconnected) {
						$("#zona_mensajes").append("<br><span style='width:100%;padding-top:10px;' class='alert alert-danger'><b>El usuario se desconecto</b></span> <div class='clearfix'></div>");
					}
					$("#zona_mensajes").attr("codigo",codigo)
					$("#zona_mensajes").attr("usuario",id)
				}
			})
			$(this).parent().find(".alfa").remove();

		})
		$("body").on("click","#cargar_imagen",function(){
			$("#imagen_gravatar").attr("src",$("#gravatar_admin").val())
		})
		$("body").on("click",'.eliminar_mensajes',function(){
			var codigo = $(this).attr("codigo");
			var id_usuario = $(this).attr("id");
			var este = $(this);
			$.ajax({
				url:"eliminar_mensajes",
				type:'post',
				data:{codigo:codigo},
				success:function(r){
					console.log(r);
					if (r ===  true) {
						este.parent().parent().hide();
					}else{
						alert("No se pudieron eliminar los mensajes");
					}
				}
			})
		});
		setInterval("buscarMensajes()",2000)
	})
function buscarMensajes(){
	var mando = 0;
	$.ajax({
		url:"get_mensajes_canal_nuevos",
		async:false,
		dataType:'json',
		success:function(r){
			puntos = r;
			$(".eliminar_mensajes").each(function(){
				codigo = $(this).attr("codigo");
				if (puntos && puntos[codigo]) {
					if ($("#zona_mensajes").attr("codigo") == codigo ) {
						$(".ver_mensajes").each(function(){
							if ($(this).attr("codigo") == codigo) {
								$(this).click();
								mando = 1;
							};
						})
					}else{

						if (typeof $(".punto_"+codigo).css("width") == "undefined" && !mando) {
							$(this).parent().append("<input type='button' class='alfa punto_"+codigo+"' style='background-color:#0F9400;border-radius:20px; width:20px;height:20px;margin-left:20px;border:none'>")
						};
						mando=0;
					}
				}
			})
			
		}
	})
	buscarNuevosContectados();
}
function mandarMensaje(mensaje,este){
	var gravatar_admin = $("#imagen_gravatar").attr('src');
	var imagen = "<img style='float:right;padding:4px;' src='"+gravatar_admin+"' width=\"50\" alt=\"Tu Imagen\">";
	var mgs = "<span style='float:right;padding-top:10px;'>"+imagen+"<b>Administrador</b>:  <br>"+mensaje+"</span> <div class='clearfix'></div>";
	var codigo_ = $("#zona_mensajes").attr("codigo");
	var usuario_id = $("#zona_mensajes").attr("usuario");

	$.ajax({
		url:"mandar_mensaje_desde_admin",
		type:"POST",
		data:{mensaje:mgs,codigo:codigo_,usuario_id:usuario_id,gravatar_admin:gravatar_admin},
		async:false,
		success:function(r){
			if (r === true) {
				$("#zona_mensajes").append(mgs);
				este.val("");
				console.log('mensaje enviado:',r);
			}else{
				alert("No se pudo enviar el mensaje")
			}
			//$("#zona_mensajes").append(mgs);
		}
	})
};
function buscarNuevosContectados(){
	var codigos = [];
	$(".ver_mensajes").each(function(){
		codigos.push($(this).attr('codigo'));
	})
	

		$.ajax({
			url:"buscar_nuevos_conectados",
			type:"POST",
			data:{codigos:codigos},
			async:false,
			success:function(r){
				console.log(r)
				html = '';
				for (var i = 0; i < r.length; i++) {
					html += '<li class="list-group-item"><img width="50" src="'+r[i].gravatar+'" alt=""> '+r[i].nombre+' ( '+r[i].email+') ';
					
			  		html += '<div class="pull-right">';
			  		html+='<input type="button" class="btn btn-default btn-xs ver_mensajes" codigo="'+r[i].identificador_canal+'" id="'+r[i].usuario_id+'" value="Ver Mensajes">'
						html+='<input type="button" class="btn btn-default btn-xs eliminar_mensajes" codigo="'+r[i].identificador_canal+'" id="'+r[i].usuario_id+'" value="Eliminar Mensajes">';
			  			html+='</div>';
			  			html+='<div class="clearfix"></div>'
			  		html+='</li>'

				};
				$("#mensajes_de_canales").append(html)
			}
		})
	
}
</script>
