<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title><?php if(isset($title)): echo $title; else: echo "Chat | hostingydomain"; endif; ?> </title>
  <?php Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('bootstrap/css/bootstrap.min') ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("jquery/jquery.min") ?>
  <?php echo Tag::js("bootstrap/js/bootstrap") ?>
</head>
<body>
  <?php View::content(); ?>
</body>
</html>
